### ISSUE TITLE
Rank values in "Upvote", "Downvote" pages are different from values in Dapp page

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#8]
**Steps:**
- create account
- open http://dev.dap.ps 
- tap to open any dapp
- open "Upvote", "Downvote" for this app and compare results for "№n in category"

<img width="701" alt="123" src="https://user-images.githubusercontent.com/4557972/60438206-794cd900-9c10-11e9-8316-0b7cf48bf2af.png">

**Comment by iamonuwa** [comment]
This error is coming from the categories. The dapps having zero category position on the vote screen are so because they are not categorized.

**Comment by iamonuwa** [comment]
> This error is coming from the categories. The dapps having zero category position on the vote screen are so because they are not categorized.

We could update it other screens to show zero for none categorized dapps.

**Comment by andytudhope** [comment]
I'm not sure I agree with your assessment here @iamonuwa... The DApps are categorized (as shown on the Profile Page), but this categorization seems not to be passed over to the Vote modal, hence the error.

Anyway, we have a new version deployed, so please test this again @churik and let me know if the same issue is still happening so that I can put a proper bounty on this.

**Comment by andytudhope** [comment]
@churik could you please test this again to make sure it has been fixed?

**Comment by andytudhope** [comment]
Fixed in #8
